### PR TITLE
OLD - chore : fix failed unit tests

### PR DESCRIPTION
**Pull request by npelletm**
Fix failed 4 unit tests
Remove dedicated header load test code in HttpResponseMessage constructor

### CODE REVIEW

**Comment by npelletm** [comment]
Only first commit will be included in this PR.
I pull another PR for the feature

**Comment by EisenbergEffect** [comment]
It would be great to separate the test fix from the feature work. I stills see it all together here.

**Comment by npelletm** [comment]
I used the same github branch.
I push two PR with fix tests and feature this day.

**Comment by npelletm** [comment]
Closedfor a new PR #177

**Pull request closed without merging**
