### PR TITLE
Comment typo error corrected in headers module

### PR DESCRIPTION
**Pull request by aftab10662**
Request you to merge the changes.

### CODE REVIEW

**Comment by aftab10662** [comment]
Typo error corrected in HttpResponseMessage module.

**Comment by EisenbergEffect** [comment]
@aftab10662  **Thank you for contributing this pull request!** We're truly excited and honored to have you as a member of our community. We look forward to working together with you to further build the Aurelia platform.

We noticed that you haven't yet signed our CLA. We would appreciate it if you would consider doing that for us. Before signing, please take a few minutes to read [our contributing guidelines](https://github.com/DurandalProject/about/blob/master/CONTRIBUTING.md). These guidelines will help get you up to speed on how our community likes to operate and how the pull request process works. Once you have read that, assuming you are in agreement, simply [sign our online CLA](https://docs.google.com/forms/d/1Npd68d32UDUKUYuCDDrW0VN5Lv8p-a6Ziaa2JFKp6Cg/viewform?c=0&w=1).

After you've signed, please ping this issue to let us know and we'll get your improvements merged in.

Thank you again!
The Aurelia Team

**Comment by bryanrsmith** [comment]
@aftab10662 If you don't mind, it would also be great if you could rebase to a single commit and update the message to match the guidelines found in CONTRIBUTING.md. Otherwise, looks good to me. Thanks!

**Comment by EisenbergEffect** [comment]
@aftab10662 Can you rebase and correct the commit message please?

**Comment by doktordirk** [comment]
@aftab10662 eg
chore(project): fix typo in header.js and update karma-jasmine-ajax

**Comment by EisenbergEffect** [comment]
Closing this since the PR provider didn't respond in over a month.

**Pull request closed without merging**
