### PR TITLE
feat(params): allow passing URL params for GET, HEAD, DELETE, OPTIONS

### LINKED ISSUE #53: Parameters
I have noticed, that you can call `client.get(url)` or other methods. Usually what you do is, that you have some parameters for the GET request or other methods. It would be nice to be able use them directly from `client`. E.g.:

```js
this.client.get('some/cool/url', { q: 'foo' });
```

instead:

```js
this.client.createRequest('some/cool/url').asGet().withParams({ q: 'foo' }).send();
```

Also this should be available for POST, PUT, PATCH, HEAD, DELETE methods. 

For PUT, PATCH and POST this will be a breaking change, but I think it is very useful.

### PR DESCRIPTION
**Pull request by Mordred**
This should fix #53

Currently I modified only `get()`, `head()`, `delete()` and `options()`. The `jsonp()`, `put()`, `patch()`, `post()` should be also modified, but first I want to know what you think about ordering arguments in these methods?

### CODE REVIEW

**Comment by EisenbergEffect** [comment]
@bryanrsmith This looks pretty good to me. Can you review and let me know what you think?

**Comment by bryanrsmith** [comment]
I think it's nice for these methods, but it might be strange on requests with bodies. We'd have to overload the methods with argument shifting to make it work as expected with either 2 or 3 args. I think it'd be more flexible to support an optional configuration object whose properties mapped to the transformers available on the request builder. That would let you make any request with either API.

It's definitely a larger project, but I was thinking it'd be great to have a `UrlBuilder` class that helped with stuff like this. Maybe as part of a new repo to share URL-related utilities that are starting to be duplicated across http-client, router, route-recognizer, etc.

`http.post(urlBuilder.map('/users/:id', { id: 123, query: 'param' }), content)`

What do you think?

**Comment by EisenbergEffect** [comment]
Could we re-purpose the path library for this?

**Comment by bryanrsmith** [comment]
Sure!

**Comment by EisenbergEffect** [comment]
Ok, I'm going to close this out for now and we can pursue extending the path library with some better url, etc. functionality. Before that, @bryanrsmith there's a couple of other router issues hangout around that I think should be looked at first. You can see a couple in the PR list and then there's one related to child routers and default routes.

**Comment by jmvtrinidad** [comment]
Hi, Im confuse on how I can add parameters with `get`, should I use `buildQueryString` from path module?
Thanks.

**Pull request closed without merging**
