### PR TITLE
Improves type information on HttpClient.configure.

### PR DESCRIPTION
**Pull request by Zoltu**

### CODE REVIEW

**Comment by bryanrsmith** [comment]
Thanks, @Zoltu. Would you mind updating the commit message to follow our contributing guidelines? Something like `feat(http-client): improve type information on HttpClient.configure`

**Comment by migajek** [comment]
this won't make sense until #71 is resolved, till then we need to use "any" anyway to allow calling methods missing in .d.ts

**Comment by bryanrsmith** [comment]
I'm going to close this for now. @Zoltu If you wouldn't mind updating your commit message and reopening the PR I'd be happy to merge it.

**Comment by Zoltu** [comment]
Sorry this took so long to get to.  It would be nice if the release notes were based on PR messages rather than commit notes. I often make small changes like this in the GitHub web UI and don't have the repo cloned locally.  Since the GitHub UI doesn't allow for editing history, updating the commit message is a bit of a pain.

**Pull request closed without merging**
