### PR TITLE
doc(http-client): yuidoc http-client, http-builder

### PR DESCRIPTION
**Pull request by jedd-ahyoung**
Begin YUIdoc inline documentation for http-client module.

### CODE REVIEW

**Comment by EisenbergEffect** [comment]
Nice work!

**Comment by jedd-ahyoung** [comment]
Hey - do you currently have the documentation app anywhere (or is it something I can run locally)? I'd like to see this in action and see if I can get yuidoc linking working, and also see how it reads in general.

**Comment by EisenbergEffect** [comment]
It's not really built yet, unfortunately.

**Comment by jedd-ahyoung** [comment]
No problem. I'll use yuidoc's live server feature. I just wanted to
determine whether you'd be supporting the full set of yuidoc syntax or a
subset (no markdown, maybe, or something).

**Comment by EisenbergEffect** [comment]
I don't think we're going to do markdown in the api docs. I'd keep it as simple as possible. We'll have other documentation to accompany this.

**Pull request merged**
