### PR TITLE
feat request-builder: add withSkipContentProcessing helper

### PR DESCRIPTION
**Pull request by sujesharukil**
add withSkipContentProcessing helper to preserve content and prevent
json stringification.

fixes issue #57

### CODE REVIEW

**Comment by EisenbergEffect** [comment]
@bryanrsmith Can you review?

**Comment by EisenbergEffect** [comment]
@bryanrsmith CLA is good if you want to merge.

**Comment by alexanderchr** [comment]
I think the helper should be called `skipContentProcessing` or maybe `withoutContentProcessing`. 'With' makes no sense in this case.

Also, the modifications to dist/ should be removed as these files are updated with version bumps.

**Comment by sujesharukil** [comment]
I qas trying to follow convention to have "with" prefix to helpers. Or am I mistaken on convention? I personally like "skipContentProcessing". I can make the changes and resubmit?

**Comment by alexanderchr** [comment]
I don't think there's any convention like that on helper naming as there are currently some that does not start with as.

Just amend the commit and force push to your branch and this pr will update itself :)

**Comment by bryanrsmith** [comment]
I agree with @alexanderchr. `skipContentProcessing` reads nicely. I think the other helpers are just named using the `with` prefix because they happened to work well with it.

It also looks like there are some merge conflicts that will need to be resolved.

Other than those adjustments this looks good to me. Thanks for contributing!

**Comment by sujesharukil** [comment]
Got it. Will do it soon.

1. Merge latest 
2. Get rid of dist changes 
3. Make changes and force push. 

Just a quick question on dist folder.. Shouldn't that be in gitignore?

**Comment by EisenbergEffect** [comment]
the dist folder is needed for actual releases.

**Comment by sujesharukil** [comment]
Got it

**Comment by sujesharukil** [comment]
There you go Gentlemen, updated as per review. Thanks :)

**Comment by EisenbergEffect** [comment]
@bryanrsmith Please review at your earliest convenience.

**Pull request merged**
