### PR TITLE
fix(headers): #152 - Made header treatment case insensitive

### PR DESCRIPTION
**Pull request by fragsalat**
Regarding the issue #152 I made the Headers treatment to be case insensitive.
I saw the Map class to fit as best for this use case but if you see a better solution tell me :)

@EisenbergEffect what do you say?

### CODE REVIEW

**Comment by fragsalat** [comment]
Sry. Had to fix the username and email of the commit again -,-

**Comment by heruan** [comment]
This should also take into accout cases like this: [http-client/http-response-message.js#L81](https://github.com/aurelia/http-client/blob/master/src/http-response-message.js#L81)
```javascript
if (this.headers && this.headers.headers)
  contentType = this.headers.headers['Content-Type'];
```

**Comment by EisenbergEffect** [comment]
@bryanrsmith Any thoughts? Looks pretty straight forward to me.

**Comment by heruan** [comment]
Note: my review does not hold, since it should work using the `Headers` object. Since I cannot delete it, please ignore it!

**Comment by fragsalat** [comment]
@heruan I'll do tomorrow. Thx for that Info

**Comment by bryanrsmith** [comment]
lgtm. @fragsalat Just curious, why the switch to `Map`? I have no objection to using a `Map`, but it does look like the majority of the changes are related to the switch to map. I think the desired outcome could have been accomplished using the object as before with only a few lines changed.

**Comment by fragsalat** [comment]
@bryanrsmith You're right. It just came with testing different solutions for there performance. I gonna change it back to an Object.

**Comment by EisenbergEffect** [comment]
Thanks all!

**Comment by fragsalat** [comment]
Yeah. Thanks :)

**Pull request merged**
